import { expect, test } from '@playwright/test'

const teacherPath = '/nurseries/nijiiro/teacher/operations'
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '保育士', exact: true }).click()
  await page.getByRole('button', { name: '保育士としてログイン', exact: true }).click()
  await expect(page).toHaveURL('/nurseries/nijiiro/teacher')
})

test('staff records, resolves and reopens a persisted near miss', async ({ page }) => {
  await page.goto(`${teacherPath}/risks`)
  await page.getByRole('button', { name: '報告を記録' }).click()
  await page.getByLabel('発生状況', { exact: true }).fill('園庭の段差につまずきそうになった')
  await page.getByLabel('対応', { exact: true }).fill('段差の周辺を確認した')
  await page.getByLabel('再発防止', { exact: true }).fill('段差に目印を設置する')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  const report = page.getByRole('article').filter({ hasText: '園庭の段差につまずきそうになった' })
  await expect(report).toBeVisible()
  await page.reload()
  await report.getByRole('button', { name: '対応を完了', exact: true }).click()
  await page.getByLabel('対応状況').selectOption('resolved')
  await expect(report).toBeVisible()
  await report.getByRole('button', { name: '対応を再開' }).click()
  await page.getByLabel('対応状況').selectOption('open')
  await expect(report).toBeVisible()
  await page.screenshot({ path: 'artifacts/staff-risk.png', fullPage: true })
})

test('staff clocks a shift with a break and reloads the saved totals', async ({ page }) => {
  await page.goto(`${teacherPath}/attendance`)
  await page.getByRole('button', { name: '出勤', exact: true }).click()
  await page.getByRole('button', { name: '休憩開始', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('休憩中')
  await page.getByRole('button', { name: '休憩終了', exact: true }).click()
  await page.getByRole('button', { name: '退勤', exact: true }).click()
  await expect(page.getByRole('article')).toHaveCount(1)
  await page.reload()
  await expect(page.getByRole('article')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '打刻を修正' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/staff-attendance.png', fullPage: true })
})

test('a plan passes draft, review, evaluation and reuse', async ({ page }) => {
  await page.goto(`${teacherPath}/plans`)
  await page.getByRole('button', { name: '計画を作成' }).click()
  const form = page.locator('form')
  await form.getByRole('combobox', { name: '種別', exact: true }).selectOption('daily')
  await form.getByLabel('ねらい', { exact: true }).fill('身近な自然を楽しむ')
  await form.getByLabel('活動内容', { exact: true }).fill('園庭で落ち葉を集める')
  await form.getByLabel('環境・援助', { exact: true }).fill('安全な範囲を確認する')
  await page.getByRole('button', { name: '下書きを保存' }).click()
  const plan = page.getByRole('article').filter({ hasText: '身近な自然を楽しむ' })
  await plan.getByRole('button', { name: '承認を依頼', exact: true }).click()
  await plan.getByRole('button', { name: '承認', exact: true }).click()
  await expect(plan).toContainText('承認済み')
  await plan.getByRole('button', { name: '評価を記入' }).click()
  await page.getByLabel('評価・振り返り', { exact: true }).fill('葉の違いに気づいていた')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await page.reload()
  await expect(plan).toContainText('葉の違いに気づいていた')
  await plan.getByRole('button', { name: 'コピー' }).click()
  await page.getByLabel('実施日').fill('2026-10-01')
  await page.getByRole('button', { name: '下書きを作成' }).click()
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.screenshot({ path: 'artifacts/staff-plans.png', fullPage: true })
})

test('individual nap observation requires explicit input and concern response', async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`${teacherPath}/nap`)
  await page.getByRole('combobox', { name: '園児', exact: true }).selectOption('c1')
  await page.getByLabel('園で定めた確認間隔（分）').fill('5')
  await page.getByRole('button', { name: '入眠を記録' }).click()
  const session = page.getByRole('article').filter({ hasText: '田中 ひなた' })
  await session.getByRole('button', { name: '姿勢・呼吸を記録' }).click()
  await expect(session.getByRole('button', { name: '確認を記録', exact: true })).toBeDisabled()
  await session.getByRole('combobox', { name: '姿勢', exact: true }).selectOption('back')
  await session.getByRole('combobox', { name: '呼吸', exact: true }).selectOption('concern')
  await session.getByLabel('気になる点', { exact: true }).fill('確認が必要な様子を記録')
  await session.getByRole('button', { name: '確認を記録', exact: true }).click()
  await expect(session).toContainText('要対応')
  await expect(session.getByRole('button', { name: '午睡終了', exact: true })).toBeDisabled()
  await session.getByLabel('対応内容').fill('担当者がその場で確認して対応した')
  await session.getByRole('button', { name: '未対応分への対応を記録' }).click()
  await page.screenshot({ path: 'artifacts/staff-nap-mobile.png', fullPage: true })
  await session.getByRole('button', { name: '午睡終了', exact: true }).click()
  await page.reload()
  await page.getByText('終了した午睡（直近7日）', { exact: true }).click()
  await page.getByText('確認履歴（1件）', { exact: true }).click()
  await expect(
    page.getByText('対応: 担当者がその場で確認して対応した', { exact: false }),
  ).toBeVisible()
  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth > window.innerWidth,
  )
  expect(overflow).toBe(false)
})
